name: Test
on: push
defaults:
  run:
    shell: bash
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up go
        uses: actions/setup-go@master
      - name: Run tests
        run: make test
